config/routes.rb
Rails.application.routes.draw do
  devise_for :user_mvcs
  resources :categories do
    resources :subcategories, only: [:index, :show, :create, :update, :destroy] do
      resources :items, only: [:new, :create]
    end
  end

  resources :subcategories, only: [:new]

  resources :items, except: [:new, :create]

  resources :admin_pages, only: [:index]

  post 'login', to: 'users#login'
  post 'signup', to: 'users#signup'
  get 'menu', to: 'categories#index'

  root "home_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories, dependent: :destroy
    validates :name, presence: true
  end
  

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :subcategory
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :subcategory_id, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :items, dependent: :destroy
  validates :name, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
  end
  

app/models/user_mvc.rb
class UserMvc < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController


  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize_request, if: :api_request?
  skip_forgery_protection
  protected

  # This method will check if the request is for JSON (API) or not
  def api_request?
    request.format.json? # The correct way to check if it's a JSON request
  end

  # This method will authorize requests for API endpoints
  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    # skip_before_action :authorize_request, only: :new


    def new
      @category = Category.new
    end
  
    def index
      categories = Category.all
      render json: categories
    end

    def show
      @category = Category.find(params[:id])
      render json: @category
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'Category not found' }, status: :not_found
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        respond_to do |format|
          format.html { redirect_to admin_pages_path, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created }
        end
      else
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        render json: @category, status: :ok
      else
        render json: @category.errors, status: :unprocessable_entity
      end
    end
  
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      head :no_content
    end
  
    private
  
    def category_params
      params.require(:category).permit(:name)
    end
  end
  

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController

  def index

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authorize_request, except: [:new, :show]
    before_action :set_subcategory, only: [:create, :new]

    def index
      if @subcategory.nil?
        render json: { error: 'Subcategory not found' }, status: :not_found
      else
        items = @subcategory.items
        render json: items
      end
    end
    
    def create
      @item = @subcategory.items.new(item_params)
      if @item.save
        render json: @item, status: :created
      else
        render json: @item.errors, status: :unprocessable_entity
      end
    end
  
    def update
      if @item.update(item_params)
        render json: @item, status: :ok
      else
        render json: @item.errors, status: :unprocessable_entity
      end
    end
  
    def destroy
      @item.destroy
      head :no_content
    end


    private
  
    def set_subcategory
      @subcategory = Subcategory.find(params[:subcategory_id])
    end
  
    def item_params
      params.require(:item).permit(:name, :price)
    end
  end
  

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # before_action :authorize_request, except: [:new, :show]
  before_action :set_category, only: [:create]
  before_action :set_subcategory, only: [:show, :update, :destroy]


  def new
    @subcategory = Subcategory.new
    @categories = Category.all
  end
  def index
    if params[:category_id]
      subcategories = @category.subcategories
    else
      subcategories = Subcategory.all
    end
    render json: subcategories
  end

  def show
    render json: @subcategory
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Subcategory not found' }, status: :not_found
  end

  def create
    @subcategory = @category.subcategories.new(subcategory_params)
    if @subcategory.save
      render json: @subcategory, status: :created
    else
      render json: @subcategory.errors, status: :unprocessable_entity
    end
  end

  def update
    if @subcategory.update(subcategory_params)
      render json: @subcategory, status: :ok
    else
      render json: @subcategory.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @subcategory.destroy
    head :no_content
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_subcategory
    @subcategory = Subcategory.find(params[:id])
  end

  def subcategory_params
    params.require(:subcategory).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize_request, except: [:login, :signup]
  
    def login
      @user = User.find_by_email(params[:email])
      if @user&.authenticate(params[:password])
        token = JsonWebToken.encode(user_id: @user.id)
        render json: { token: token, message: 'Successfully logged in' }, status: :ok
      else
        render json: { error: 'Invalid email or password' }, status: :unauthorized
      end
    end


    def signup
      @user = User.new(signup_params)
      if @user.save
        token = JsonWebToken.encode(user_id: @user.id)
        render json: { token: token, message: 'Account created successfully' }, status: :created
      else
        render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
      end
    end


    private
    def signup_params
      params.require(:users).permit(:email, :password)
    end
  end
  

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/user_mvcs_helper.rb
module UserMvcsHelper
end

app/views/admin_pages/index.html.erb
<div>
  <%=link_to "Create category", new_category_path %>
</div>

<div>
  <%=link_to "Create subcategory", new_subcategory_url %>
</div>

<div>
  <%=link_to "Create item" %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, "Category Name" %>
    <%= form.text_field :name, placeholder: "Enter category name" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Category" %>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/home_pages/index.html.erb
<h1>hello from homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
</head>

<body>
<div>
  <%= link_to "Restaurant", root_path %>
</div>
<div>
  <% if user_mvc_signed_in? %>
    <div>
      Hello, <%= current_user_mvc.email %>
    </div>
    <div>
      <%= button_to "Log Out", destroy_user_mvc_session_path, method: :delete %>
    </div>
  <% else %>
    <div>
      <%= button_to "Log In", new_user_mvc_session_url, method: "get" %>
    </div>
    <div>
      <%= button_to "Sign Up", new_user_mvc_registration_url, method: "get" %>
    </div>
  <% end %>
</div>

<div>
  <div>
    Home
  </div>
  <div>
    <%= link_to "Admin", admin_pages_path %>
  </div>
</div>

<% if alert || notice %>
  <div>
    <% if notice %>
      <div>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div>
        <%= alert %>
      </div>
    <% end %>
  </div>
<% end %>

<%= yield %>
</body>
</html>

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory) do |form| %>
  <div class="field">
    <%= form.label :parent_category, "Parent Category" %>
    <%= form.collection_select :category_id, categories, :id, :name, prompt: "Select a parent category" %>
  </div>

  <div class="field">
    <%= form.label :name, "Subcategory Name" %>
    <%= form.text_field :name, placeholder: "Enter subcategory name" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Subcategory" %>
  </div>
<% end %>

app/views/subcategories/new.html.erb
<%= render 'form', subcategory: @subcategory %>